language: go
go:
  - "1.10.x"
  - "1.11.x"
  - master
env:
  - GO111MODULE=on GOLANGCI_LINT_VERSION=1.13.2
before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v$GOLANGCI_LINT_VERSION
script:
      - golangci-lint run
      - go test -v ./...
